# ============================================================
# ATP Bot – Data
# ============================================================

PLAYERS = {
    "alcaraz":        {"name": "Carlos Alcaraz",        "rank": 1,  "country": "ESP", "style": "All-Court Player",               "style_key": "allcourt",       "loses_to": "all-court like Sinner, Djokovic",       "wins_against": "counterpunchers like Medvedev, Norrie", "surface": "Excellent on all; best clay & grass"},
    "sinner":         {"name": "Jannik Sinner",          "rank": 2,  "country": "ITA", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "all-court like Alcaraz, Djokovic",      "wins_against": "big servers like Fritz, Hurkacz",       "surface": "Hard court specialist; strong on fast"},
    "djokovic":       {"name": "Novak Djokovic",         "rank": 3,  "country": "SRB", "style": "All-Court / Counterpuncher",     "style_key": "counterpuncher", "loses_to": "Sinner, Alcaraz (physically demanding)", "wins_against": "big servers like Zverev, Berrettini",   "surface": "Versatile; strongest on hard & clay"},
    "zverev":         {"name": "Alexander Zverev",       "rank": 4,  "country": "GER", "style": "Big Serving Baseliner",          "style_key": "baseliner",      "loses_to": "all-court like Alcaraz, Djokovic",      "wins_against": "counterpunchers like Norrie, De Minaur","surface": "Prefers fast hard; high ace%"},
    "musetti":        {"name": "Lorenzo Musetti",        "rank": 5,  "country": "ITA", "style": "All-Court / Serve-Volleyer",     "style_key": "bigserver",      "loses_to": "aggressive baseliners like Sinner, Draper","wins_against": "big servers like Shelton, Fritz",      "surface": "Best on slow clay; improving on hard"},
    "deminaur":       {"name": "Alex de Minaur",         "rank": 6,  "country": "AUS", "style": "Counterpuncher",                 "style_key": "counterpuncher", "loses_to": "big servers like Bublik, Opelka",        "wins_against": "aggressive baseliners like Rublev, Draper","surface": "Excellent on fast hard; strong mover"},
    "fritz":          {"name": "Taylor Fritz",           "rank": 7,  "country": "USA", "style": "Big Server / Baseliner",         "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Top on fast hard; strong serve"},
    "shelton":        {"name": "Ben Shelton",            "rank": 8,  "country": "USA", "style": "Big Server / Attacker",          "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud, Paul",      "surface": "Strong on fast hard; explosive serve"},
    "auger-aliassime":{"name": "Felix Auger-Aliassime",  "rank": 9,  "country": "CAN", "style": "All-Court Player",               "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud, Rublev",    "surface": "Prefers fast; strong serve & forehand"},
    "faa":            {"name": "Felix Auger-Aliassime",  "rank": 9,  "country": "CAN", "style": "All-Court Player",               "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud, Rublev",    "surface": "Prefers fast; strong serve & forehand"},
    "bublik":         {"name": "Alexander Bublik",       "rank": 10, "country": "KAZ", "style": "Big Server / Unpredictable",     "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Sinner", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Top on fast indoor; serve-and-volley"},
    "medvedev":       {"name": "Daniil Medvedev",        "rank": 11, "country": "RUS", "style": "Counterpuncher / Defender",      "style_key": "counterpuncher", "loses_to": "all-court like Alcaraz, Sinner",         "wins_against": "aggressive baseliners like Rublev, Draper","surface": "Hard court specialist; best slow hard"},
    "mensik":         {"name": "Jakub Mensik",           "rank": 12, "country": "CZE", "style": "Aggressive Baseliner / Big Server","style_key": "bigserver",    "loses_to": "counterpunchers like Norrie, De Minaur", "wins_against": "solid baseliners like Ruud, Paul",      "surface": "Good on medium-fast hard"},
    "ruud":           {"name": "Casper Ruud",            "rank": 13, "country": "NOR", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Shelton, Fritz",        "wins_against": "all-court like Musetti; weaker attackers","surface": "Top on slow clay; decent on hard"},
    "draper":         {"name": "Jack Draper",            "rank": 14, "country": "GBR", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like Medvedev, Sinner",  "wins_against": "big servers like Fritz, Hurkacz",       "surface": "Strong on fast hard; powerful lefty"},
    "cobolli":        {"name": "Flavio Cobolli",         "rank": 15, "country": "ITA", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Bublik, Shelton",       "wins_against": "attacking players like Draper, Fils",   "surface": "Adaptable; medium-paced courts"},
    "khachanov":      {"name": "Karen Khachanov",        "rank": 16, "country": "RUS", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Strong on fast hard; powerful game"},
    "rublev":         {"name": "Andrey Rublev",          "rank": 17, "country": "RUS", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like Medvedev, Fokina",  "wins_against": "big servers like Fritz, Hurkacz",       "surface": "Versatile; best on medium-fast hard"},
    "rune":           {"name": "Holger Rune",            "rank": 18, "country": "DEN", "style": "All-Court",                      "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Medvedev","wins_against": "aggressive baseliners like Mensik, Rublev","surface": "Adaptable; clay and hard"},
    "fokina":         {"name": "Alejandro Davidovich Fokina","rank":19,"country":"ESP","style": "Counterpuncher / Baseliner",     "style_key": "counterpuncher", "loses_to": "consistent baseliners like Rublev, Sinner","wins_against": "all-court & attackers like Fils, Musetti","surface": "Best on slow clay; good outdoor hard"},
    "cerundolo":      {"name": "Francisco Cerundolo",    "rank": 20, "country": "ARG", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "aggressive baseliners like Alcaraz, Sinner","wins_against": "counterpunchers like Norrie",           "surface": "Clay preferred; slow courts"},
    "darderi":        {"name": "Luciano Darderi",        "rank": 21, "country": "ITA", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud, Paul",      "surface": "Best on clay; adaptable"},
    "tiafoe":         {"name": "Frances Tiafoe",         "rank": 22, "country": "USA", "style": "All-Court",                      "style_key": "allcourt",       "loses_to": "big servers like Fritz, Opelka",         "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Prefers fast hard; energetic style"},
    "lehecka":        {"name": "Jiri Lehecka",           "rank": 23, "country": "CZE", "style": "Big Server / Aggressive Baseliner","style_key": "bigserver",    "loses_to": "counterpunchers like Medvedev, Sinner",  "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Fast courts; indoor specialist"},
    "paul":           {"name": "Tommy Paul",             "rank": 24, "country": "USA", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Shelton, Hurkacz",      "wins_against": "counterpunchers like Norrie",           "surface": "Versatile; good on hard"},
    "griekspoor":     {"name": "Tallon Griekspoor",      "rank": 25, "country": "NED", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "big servers like Fritz, Hurkacz",       "surface": "Fast hard courts; indoor specialist"},
    "vacherot":       {"name": "Valentin Vacherot",      "rank": 26, "country": "FRA", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Bublik, Lehecka",       "wins_against": "counterpunchers; weaker baseliners",    "surface": "Adaptable; medium pace"},
    "tien":           {"name": "Learner Tien",           "rank": 27, "country": "USA", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like Medvedev, Norrie",  "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Fast hard courts"},
    "rinderknech":    {"name": "Arthur Rinderknech",     "rank": 28, "country": "FRA", "style": "Big Server",                     "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Paul, Mensik",    "surface": "Fast hard; serve-driven game"},
    "norrie":         {"name": "Cameron Norrie",         "rank": 29, "country": "GBR", "style": "Counterpuncher / Solid Baseliner","style_key": "counterpuncher","loses_to": "big servers like Fritz, Hurkacz",        "wins_against": "aggressive baseliners like Rublev, Draper","surface": "Best on hard; good mover"},
    "nakashima":      {"name": "Brandon Nakashima",      "rank": 30, "country": "USA", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "aggressive baseliners like Alcaraz, Sinner","wins_against": "counterpunchers; weaker baseliners",   "surface": "Fast hard courts"},
    "etcheverry":     {"name": "Tomas Martin Etcheverry","rank": 31, "country": "ARG", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Lehecka, Shelton",      "wins_against": "counterpunchers; clay baseliners",      "surface": "Slow clay preferred"},
    "fils":           {"name": "Arthur Fils",            "rank": 32, "country": "FRA", "style": "All-Court / Aggressive",         "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Versatile; clay and hard"},
    "humbert":        {"name": "Ugo Humbert",            "rank": 34, "country": "FRA", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like Medvedev, Norrie",  "wins_against": "big servers like Fritz",                "surface": "Fast indoor hard; lefty serve"},
    "fonseca":        {"name": "Joao Fonseca",           "rank": 35, "country": "BRA", "style": "Aggressive Baseliner",           "style_key": "baseliner",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud, Paul",      "surface": "Medium-fast hard courts"},
    "korda":          {"name": "Sebastian Korda",        "rank": 37, "country": "USA", "style": "All-Court / Aggressive",         "style_key": "allcourt",       "loses_to": "counterpunchers like Medvedev, Norrie",  "wins_against": "big servers like Hurkacz",              "surface": "Fast hard courts"},
    "diallo":         {"name": "Gabriel Diallo",         "rank": 38, "country": "CAN", "style": "Big Server",                     "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Fast hard courts"},
    "shapovalov":     {"name": "Denis Shapovalov",       "rank": 39, "country": "CAN", "style": "Aggressive All-Court",           "style_key": "allcourt",       "loses_to": "counterpunchers like Medvedev, Norrie",  "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Fast hard & grass; lefty game"},
    "tabilo":         {"name": "Alejandro Tabilo",       "rank": 40, "country": "CHI", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Fritz, Opelka",         "wins_against": "counterpunchers like Norrie",           "surface": "Medium pace; clay & hard"},
    "brooksby":       {"name": "Jenson Brooksby",        "rank": 41, "country": "USA", "style": "Counterpuncher / Defender",      "style_key": "counterpuncher", "loses_to": "big servers like Shelton, Lehecka",      "wins_against": "aggressive baseliners like Draper",     "surface": "Versatile; strong return game"},
    "dimitrov":       {"name": "Grigor Dimitrov",        "rank": 42, "country": "BUL", "style": "All-Court",                      "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "big servers like Hurkacz, Fritz",       "surface": "Versatile; hard and clay"},
    "tsitsipas":      {"name": "Stefanos Tsitsipas",     "rank": 43, "country": "GRE", "style": "All-Court",                      "style_key": "allcourt",       "loses_to": "counterpunchers like Medvedev, Sinner",  "wins_against": "solid baseliners like Ruud",            "surface": "Clay and hard; best on slow courts"},
    "hurkacz":        {"name": "Hubert Hurkacz",         "rank": 53, "country": "POL", "style": "Big Server / All-Court",         "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Sinner", "wins_against": "solid baseliners like Paul, Ruud",      "surface": "Fast hard; excellent on grass"},
    "baez":           {"name": "Sebastian Baez",         "rank": 52, "country": "ARG", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Shelton, Lehecka",      "wins_against": "counterpunchers; clay baseliners",      "surface": "Slow clay"},
    "djere":          {"name": "Laslo Djere",            "rank": 55, "country": "SRB", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Lehecka, Shelton",      "wins_against": "counterpunchers; clay baseliners",      "surface": "Slow clay"},
    "muller":         {"name": "Alexandre Muller",       "rank": 56, "country": "FRA", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Fritz, Hurkacz",        "wins_against": "counterpunchers; weaker baseliners",    "surface": "Versatile"},
    "monfils":        {"name": "Gael Monfils",           "rank": 60, "country": "FRA", "style": "Aggressive All-Court",           "style_key": "allcourt",       "loses_to": "counterpunchers like Medvedev, Norrie",  "wins_against": "solid baseliners",                      "surface": "Fast hard courts; athletic game"},
    "fucsovics":      {"name": "Marton Fucsovics",       "rank": 70, "country": "HUN", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Fritz, Bublik",         "wins_against": "rhythm players",                        "surface": "Hard courts"},
    "machac":         {"name": "Tomas Machac",           "rank": 50, "country": "CZE", "style": "All-Court / Aggressive",         "style_key": "allcourt",       "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners like Ruud",            "surface": "Versatile; hard and clay"},
    "opelka":         {"name": "Reilly Opelka",          "rank": 57, "country": "USA", "style": "Big Server",                     "style_key": "bigserver",      "loses_to": "counterpunchers like De Minaur, Norrie", "wins_against": "solid baseliners; rhythm players",      "surface": "Fast hard; elite serve"},
    "kecmanovic":     {"name": "Miomir Kecmanovic",      "rank": 58, "country": "SRB", "style": "Solid Baseliner",                "style_key": "counterpuncher", "loses_to": "big servers like Shelton, Opelka",       "wins_against": "counterpunchers; weaker baseliners",    "surface": "Hard courts"},
    "bergs":          {"name": "Zizou Bergs",            "rank": 47, "country": "BEL", "style": "All-Court",                      "style_key": "allcourt",       "loses_to": "big servers like Bublik, Opelka",        "wins_against": "counterpunchers like Norrie",           "surface": "Versatile"},
}

# Aliases voor veelgebruikte namen
ALIASES = {
    "carlos": "alcaraz",
    "jannik": "sinner",
    "novak": "djokovic",
    "sascha": "zverev",
    "sasja": "zverev",
    "alex": "deminaur",
    "taylor": "fritz",
    "ben": "shelton",
    "felix": "auger-aliassime",
    "daniil": "medvedev",
    "jakub": "mensik",
    "casper": "ruud",
    "jack": "draper",
    "holger": "rune",
    "andrey": "rublev",
    "arthur": "fils",
    "tommy": "paul",
    "ugo": "humbert",
    "joao": "fonseca",
    "denis": "shapovalov",
    "hubert": "hurkacz",
    "stefanos": "tsitsipas",
    "grigor": "dimitrov",
    "tallon": "griekspoor",
    "cameron": "norrie",
    "brandon": "nakashima",
    "gael": "monfils",
    "gaël": "monfils",
    "learner": "tien",
    "gabriel": "diallo",
    "flavio": "cobolli",
    "luciano": "darderi",
    "laslo": "djere",
    "alejandro": "fokina",
    "francisco": "cerundolo",
    "sebastian k": "korda",
    "sebastian b": "baez",
    "tomas m": "machac",
}

TOURNAMENTS = {
    "australian open": {"name": "Australian Open", "category": "Grand Slam",   "surface": "Hard (outdoor)", "speed": 1.12, "speed_cat": "Medium-Fast", "winner_2025": "Sinner",       "finalist_2025": "Zverev",          "winner_2024": "Sinner",       "finalist_2024": "Medvedev"},
    "roland garros":   {"name": "Roland Garros",   "category": "Grand Slam",   "surface": "Clay",           "speed": 0.68, "speed_cat": "Slow",         "winner_2025": "Alcaraz",      "finalist_2025": "Sinner",          "winner_2024": "Alcaraz",      "finalist_2024": "Zverev"},
    "wimbledon":       {"name": "Wimbledon",        "category": "Grand Slam",   "surface": "Grass",          "speed": 1.11, "speed_cat": "Medium-Fast", "winner_2025": "Sinner",       "finalist_2025": "Alcaraz",         "winner_2024": "Alcaraz",      "finalist_2024": "Djokovic"},
    "us open":         {"name": "US Open",          "category": "Grand Slam",   "surface": "Hard (outdoor)", "speed": 0.97, "speed_cat": "Medium",       "winner_2025": "Alcaraz",      "finalist_2025": "Sinner",          "winner_2024": "Sinner",       "finalist_2024": "Fritz"},
    "indian wells":    {"name": "Indian Wells Masters","category":"Masters 1000","surface":"Hard (outdoor)",  "speed": 0.73, "speed_cat": "Medium-Slow",  "winner_2025": "Draper",       "finalist_2025": "Rune",            "winner_2024": "Alcaraz",      "finalist_2024": "Medvedev"},
    "miami":           {"name": "Miami Masters",    "category": "Masters 1000", "surface": "Hard (outdoor)", "speed": 1.18, "speed_cat": "Medium-Fast",  "winner_2025": "Mensik",       "finalist_2025": "Djokovic",        "winner_2024": "Sinner",       "finalist_2024": "Medvedev"},
    "monte carlo":     {"name": "Monte Carlo Masters","category":"Masters 1000","surface": "Clay",           "speed": 0.56, "speed_cat": "Slow",         "winner_2025": "Alcaraz",      "finalist_2025": "Musetti",         "winner_2024": "Tsitsipas",    "finalist_2024": "Rublev"},
    "madrid":          {"name": "Madrid Masters",   "category": "Masters 1000", "surface": "Clay",           "speed": 0.79, "speed_cat": "Medium-Slow",  "winner_2025": "Ruud",         "finalist_2025": "Draper",          "winner_2024": "Zverev",       "finalist_2024": "Musetti"},
    "rome":            {"name": "Rome Masters",     "category": "Masters 1000", "surface": "Clay",           "speed": 0.61, "speed_cat": "Slow",         "winner_2025": "Alcaraz",      "finalist_2025": "Sinner",          "winner_2024": "Zverev",       "finalist_2024": "Alcaraz"},
    "canada":          {"name": "Canada Masters",   "category": "Masters 1000", "surface": "Hard (outdoor)", "speed": 1.00, "speed_cat": "Medium",       "winner_2025": "Shelton",      "finalist_2025": "Khachanov",       "winner_2024": "Popyrin",      "finalist_2024": "Rublev"},
    "toronto":         {"name": "Canada Masters",   "category": "Masters 1000", "surface": "Hard (outdoor)", "speed": 1.00, "speed_cat": "Medium",       "winner_2025": "Shelton",      "finalist_2025": "Khachanov",       "winner_2024": "Popyrin",      "finalist_2024": "Rublev"},
    "cincinnati":      {"name": "Cincinnati Masters","category": "Masters 1000", "surface": "Hard (outdoor)", "speed": 1.19, "speed_cat": "Medium-Fast",  "winner_2025": "Alcaraz",      "finalist_2025": "Sinner",          "winner_2024": "Sinner",       "finalist_2024": "Tiafoe"},
    "shanghai":        {"name": "Shanghai Masters", "category": "Masters 1000", "surface": "Hard (outdoor)", "speed": 1.08, "speed_cat": "Medium-Fast",  "winner_2025": "Vacherot",     "finalist_2025": "Rinderknech",     "winner_2024": "Sinner",       "finalist_2024": "Fritz"},
    "paris":           {"name": "Paris Masters",    "category": "Masters 1000", "surface": "Hard (indoor)",  "speed": 0.97, "speed_cat": "Medium",       "winner_2025": "Sinner",       "finalist_2025": "Auger-Aliassime", "winner_2024": "Zverev",       "finalist_2024": "Rune"},
    "paris masters":   {"name": "Paris Masters",    "category": "Masters 1000", "surface": "Hard (indoor)",  "speed": 0.97, "speed_cat": "Medium",       "winner_2025": "Sinner",       "finalist_2025": "Auger-Aliassime", "winner_2024": "Zverev",       "finalist_2024": "Rune"},
    "dubai":           {"name": "Dubai Duty Free",  "category": "ATP 500",      "surface": "Hard (outdoor)", "speed": 1.01, "speed_cat": "Medium",       "winner_2025": "Tsitsipas",    "finalist_2025": "Auger-Aliassime", "winner_2024": "Sinner",       "finalist_2024": "Shelton"},
    "acapulco":        {"name": "Acapulco (Mexican Open)","category":"ATP 500", "surface": "Hard (outdoor)", "speed": 1.16, "speed_cat": "Medium-Fast",  "winner_2025": "Machac",       "finalist_2025": "Shelton",         "winner_2024": "Shelton",      "finalist_2024": "De Minaur"},
    "rotterdam":       {"name": "Rotterdam (ABN AMRO)","category":"ATP 500",    "surface": "Hard (indoor)",  "speed": 0.91, "speed_cat": "Medium",       "winner_2025": "Alcaraz",      "finalist_2025": "De Minaur",       "winner_2024": "Griekspoor",   "finalist_2024": "De Jong"},
    "rio":             {"name": "Rio de Janeiro",   "category": "ATP 500",      "surface": "Clay",           "speed": 1.01, "speed_cat": "Medium",       "winner_2025": "Baez",         "finalist_2025": "Cerundolo",       "winner_2024": "Cerundolo",    "finalist_2024": "Navone"},
    "doha":            {"name": "Doha (Qatar Open)", "category": "ATP 500",     "surface": "Hard (outdoor)", "speed": 0.90, "speed_cat": "Medium",       "winner_2025": "Rublev",       "finalist_2025": "Draper",          "winner_2024": "Sinner",       "finalist_2024": "Medvedev"},
    "barcelona":       {"name": "Barcelona Open",   "category": "ATP 500",      "surface": "Clay",           "speed": 0.56, "speed_cat": "Slow",         "winner_2025": "Rune",         "finalist_2025": "Alcaraz",         "winner_2024": "Alcaraz",      "finalist_2024": "Tsitsipas"},
    "hamburg":         {"name": "Hamburg Open",     "category": "ATP 500",      "surface": "Clay",           "speed": 0.56, "speed_cat": "Slow",         "winner_2025": "Cobolli",      "finalist_2025": "Darderi",         "winner_2024": "Zverev",       "finalist_2024": "Khachanov"},
    "washington":      {"name": "Washington (Citi Open)","category":"ATP 500",  "surface": "Hard (outdoor)", "speed": 1.15, "speed_cat": "Medium-Fast",  "winner_2025": "De Minaur",    "finalist_2025": "Fokina",          "winner_2024": "Fritz",        "finalist_2024": "Shelton"},
    "beijing":         {"name": "Beijing (China Open)","category":"ATP 500",    "surface": "Hard (outdoor)", "speed": 1.06, "speed_cat": "Medium-Fast",  "winner_2025": "Sinner",       "finalist_2025": "Tien",            "winner_2024": "Sinner",       "finalist_2024": "Medvedev"},
    "tokyo":           {"name": "Tokyo (Japan Open)","category": "ATP 500",     "surface": "Hard (outdoor)", "speed": 1.17, "speed_cat": "Medium-Fast",  "winner_2025": "Alcaraz",      "finalist_2025": "Fritz",           "winner_2024": "Fritz",        "finalist_2024": "Fils"},
    "vienna":          {"name": "Vienna (Erste Bank Open)","category":"ATP 500","surface": "Hard (indoor)",  "speed": 1.22, "speed_cat": "Medium-Fast",  "winner_2025": "Sinner",       "finalist_2025": "Zverev",          "winner_2024": "Djokovic",     "finalist_2024": "Sinner"},
    "basel":           {"name": "Basel (Swiss Indoors)","category":"ATP 500",   "surface": "Hard (indoor)",  "speed": 1.37, "speed_cat": "Fast",         "winner_2025": "Fonseca",      "finalist_2025": "Fokina",          "winner_2024": "Fritz",        "finalist_2024": "Cerundolo"},
    "halle":           {"name": "Halle (Terra Wortmann)","category":"ATP 500",  "surface": "Grass",          "speed": 1.26, "speed_cat": "Medium-Fast",  "winner_2025": "Bublik",       "finalist_2025": "Medvedev",        "winner_2024": "Sinner",       "finalist_2024": "Hurkacz"},
    "queens":          {"name": "Queen's Club",     "category": "ATP 500",      "surface": "Grass",          "speed": 1.33, "speed_cat": "Fast",         "winner_2025": "Alcaraz",      "finalist_2025": "Lehecka",         "winner_2024": "Fritz",        "finalist_2024": "Shelton"},
    "queen's":         {"name": "Queen's Club",     "category": "ATP 500",      "surface": "Grass",          "speed": 1.33, "speed_cat": "Fast",         "winner_2025": "Alcaraz",      "finalist_2025": "Lehecka",         "winner_2024": "Fritz",        "finalist_2024": "Shelton"},
    "stuttgart":       {"name": "Stuttgart (Boss Open)","category":"ATP 500",   "surface": "Grass",          "speed": 1.40, "speed_cat": "Fast",         "winner_2025": "Fritz",        "finalist_2025": "Zverev",          "winner_2024": "Draper",       "finalist_2024": "Struff"},
    "dallas":          {"name": "Dallas Open",      "category": "ATP 500",      "surface": "Hard (indoor)",  "speed": 1.49, "speed_cat": "Fast",         "winner_2025": "Shapovalov",   "finalist_2025": "Ruud",            "winner_2024": "Fritz",        "finalist_2024": "Nakashima"},
    "brisbane":        {"name": "Brisbane International","category":"ATP 250",  "surface": "Hard (outdoor)", "speed": 1.20, "speed_cat": "Medium-Fast",  "winner_2025": "Lehecka",      "finalist_2025": "Opelka",          "winner_2024": "Korda",        "finalist_2024": "Humbert"},
    "auckland":        {"name": "Auckland (ASB Classic)","category":"ATP 250",  "surface": "Hard (outdoor)", "speed": 1.04, "speed_cat": "Medium",       "winner_2025": "Monfils",      "finalist_2025": "Bergs",           "winner_2024": "Paul",         "finalist_2024": "Lehecka"},
    "montpellier":     {"name": "Montpellier",      "category": "ATP 250",      "surface": "Hard (indoor)",  "speed": 1.44, "speed_cat": "Fast",         "winner_2025": "Auger-Aliassime","finalist_2025": "Kovacevic",     "winner_2024": "Humbert",      "finalist_2024": "Mannarino"},
    "marseille":       {"name": "Marseille (Open 13)","category":"ATP 250",     "surface": "Hard (indoor)",  "speed": 1.36, "speed_cat": "Fast",         "winner_2025": "Humbert",      "finalist_2025": "Medjedovic",      "winner_2024": "Humbert",      "finalist_2024": "Mannarino"},
    "delray beach":    {"name": "Delray Beach Open","category": "ATP 250",      "surface": "Hard (outdoor)", "speed": 1.36, "speed_cat": "Fast",         "winner_2025": "Kecmanovic",   "finalist_2025": "Fokina",          "winner_2024": "Mensik",       "finalist_2024": "Cerundolo"},
    "santiago":        {"name": "Santiago (Chile Open)","category":"ATP 250",   "surface": "Clay",           "speed": 0.68, "speed_cat": "Slow",         "winner_2025": "Djere",        "finalist_2025": "Baez",            "winner_2024": "Tabilo",       "finalist_2024": "Korda"},
    "buenos aires":    {"name": "Buenos Aires",     "category": "ATP 250",      "surface": "Clay",           "speed": 0.54, "speed_cat": "Very Slow",    "winner_2025": "Fonseca",      "finalist_2025": "Baez",            "winner_2024": "Fonseca",      "finalist_2024": "Baez"},
    "marrakech":       {"name": "Marrakech",        "category": "ATP 250",      "surface": "Clay",           "speed": 0.80, "speed_cat": "Medium-Slow",  "winner_2025": "Darderi",      "finalist_2025": "Davidovich Fokina","winner_2024": "Tabilo",      "finalist_2024": "Munar"},
    "bucharest":       {"name": "Bucharest (Tiriac Open)","category":"ATP 250", "surface": "Clay",           "speed": 0.42, "speed_cat": "Very Slow",    "winner_2025": "Cobolli",      "finalist_2025": "Fils",            "winner_2024": "Cobolli",      "finalist_2024": "Fils"},
    "houston":         {"name": "Houston (U.S. Clay Court)","category":"ATP 250","surface":"Clay",           "speed": 0.72, "speed_cat": "Medium-Slow",  "winner_2025": "Brooksby",     "finalist_2025": "Tiafoe",          "winner_2024": "Paul",         "finalist_2024": "Etcheverry"},
    "geneva":          {"name": "Geneva Open",      "category": "ATP 250",      "surface": "Clay",           "speed": 0.71, "speed_cat": "Medium-Slow",  "winner_2025": "Djokovic",     "finalist_2025": "Rublev",          "winner_2024": "Shelton",      "finalist_2024": "Rublev"},
    "s-hertogenbosch": {"name": "s-Hertogenbosch",  "category": "ATP 250",      "surface": "Grass",          "speed": 0.99, "speed_cat": "Medium",       "winner_2025": "Diallo",       "finalist_2025": "Griekspoor",      "winner_2024": "Rublev",       "finalist_2024": "Cerundolo"},
    "den bosch":       {"name": "s-Hertogenbosch",  "category": "ATP 250",      "surface": "Grass",          "speed": 0.99, "speed_cat": "Medium",       "winner_2025": "Diallo",       "finalist_2025": "Griekspoor",      "winner_2024": "Rublev",       "finalist_2024": "Cerundolo"},
    "mallorca":        {"name": "Mallorca Championships","category":"ATP 250",  "surface": "Grass",          "speed": 1.04, "speed_cat": "Medium",       "winner_2025": "Griekspoor",   "finalist_2025": "Bublik",          "winner_2024": "Lehecka",      "finalist_2024": "Rune"},
    "eastbourne":      {"name": "Eastbourne",       "category": "ATP 250",      "surface": "Grass",          "speed": 0.76, "speed_cat": "Medium-Slow",  "winner_2025": "Fritz",        "finalist_2025": "Humbert",         "winner_2024": "Draper",       "finalist_2024": "Bublik"},
    "bastad":          {"name": "Bastad (Swedish Open)","category":"ATP 250",   "surface": "Clay",           "speed": 0.85, "speed_cat": "Medium-Slow",  "winner_2025": "Darderi",      "finalist_2025": "Munar",           "winner_2024": "Korda",        "finalist_2024": "Davidovich Fokina"},
    "umag":            {"name": "Umag (Croatia Open)","category":"ATP 250",     "surface": "Clay",           "speed": 0.74, "speed_cat": "Medium-Slow",  "winner_2025": "Darderi",      "finalist_2025": "Baez",            "winner_2024": "Popyrin",      "finalist_2024": "Kecmanovic"},
    "gstaad":          {"name": "Gstaad (Swiss Open)","category":"ATP 250",     "surface": "Clay",           "speed": 1.03, "speed_cat": "Medium",       "winner_2025": "Bublik",       "finalist_2025": "Tabilo",          "winner_2024": "Tabilo",       "finalist_2024": "Zverev"},
    "kitzbuhel":       {"name": "Kitzbühel",        "category": "ATP 250",      "surface": "Clay",           "speed": 0.83, "speed_cat": "Medium-Slow",  "winner_2025": "Bublik",       "finalist_2025": "Darderi",         "winner_2024": "Zverev",       "finalist_2024": "Baez"},
    "los cabos":       {"name": "Los Cabos (Mifel Open)","category":"ATP 250",  "surface": "Hard (outdoor)", "speed": 0.95, "speed_cat": "Medium",       "winner_2025": "Shapovalov",   "finalist_2025": "Korda",           "winner_2024": "Mensik",       "finalist_2024": "Fritz"},
    "winston-salem":   {"name": "Winston-Salem Open","category":"ATP 250",      "surface": "Hard (outdoor)", "speed": 1.07, "speed_cat": "Medium",       "winner_2025": "Fucsovics",    "finalist_2025": "Van de Zandschulp","winner_2024": "Fritz",       "finalist_2024": "Paul"},
    "chengdu":         {"name": "Chengdu Open",     "category": "ATP 250",      "surface": "Hard (outdoor)", "speed": 1.16, "speed_cat": "Medium-Fast",  "winner_2025": "Tabilo",       "finalist_2025": "Musetti",         "winner_2024": "Rublev",       "finalist_2024": "Medvedev"},
    "hangzhou":        {"name": "Hangzhou Open",    "category": "ATP 250",      "surface": "Hard (outdoor)", "speed": 1.45, "speed_cat": "Fast",         "winner_2025": "Bublik",       "finalist_2025": "Tien",            "winner_2024": "Shelton",      "finalist_2024": "Fils"},
    "almaty":          {"name": "Almaty (Kazakhstan Open)","category":"ATP 250","surface": "Hard (indoor)",  "speed": 1.20, "speed_cat": "Medium-Fast",  "winner_2025": "Medvedev",     "finalist_2025": "Shevchenko",      "winner_2024": "Bublik",       "finalist_2024": "Baez"},
    "stockholm":       {"name": "Stockholm Open",   "category": "ATP 250",      "surface": "Hard (indoor)",  "speed": 0.92, "speed_cat": "Medium",       "winner_2025": "Ruud",         "finalist_2025": "Auger-Aliassime", "winner_2024": "Paul",         "finalist_2024": "Griekspoor"},
    "brussels":        {"name": "Brussels (European Open)","category":"ATP 250","surface": "Hard (indoor)",  "speed": 1.33, "speed_cat": "Fast",         "winner_2025": "Auger-Aliassime","finalist_2025": "Lehecka",       "winner_2024": "Bublik",       "finalist_2024": "Mannarino"},
    "athens":          {"name": "Athens",           "category": "ATP 250",      "surface": "Hard (indoor)",  "speed": 1.41, "speed_cat": "Fast",         "winner_2025": "Djokovic",     "finalist_2025": "Muller",          "winner_2024": "Tsitsipas",    "finalist_2024": "Rublev"},
    "metz":            {"name": "Metz (Moselle Open)","category":"ATP 250",     "surface": "Hard (indoor)",  "speed": 1.36, "speed_cat": "Fast",         "winner_2025": "Tien",         "finalist_2025": "Norrie",          "winner_2024": "Humbert",      "finalist_2024": "Lehecka"},
    "atp finals":      {"name": "ATP Finals",       "category": "ATP Finals",   "surface": "Hard (indoor)",  "speed": 1.35, "speed_cat": "Fast",         "winner_2025": "Sinner",       "finalist_2025": "Alcaraz",         "winner_2024": "Sinner",       "finalist_2024": "Fritz"},
    "tour finals":     {"name": "ATP Finals",       "category": "ATP Finals",   "surface": "Hard (indoor)",  "speed": 1.35, "speed_cat": "Fast",         "winner_2025": "Sinner",       "finalist_2025": "Alcaraz",         "winner_2024": "Sinner",       "finalist_2024": "Fritz"},
}

# Speelstijl matchup tabel
# Hoeveel punten krijgt speler1 voor speelstijl matchup vs speler2
# Positief = speler1 voordeel, negatief = speler2 voordeel
STYLE_MATCHUP = {
    ("allcourt", "counterpuncher"): 2,
    ("allcourt", "baseliner"): 1,
    ("allcourt", "bigserver"): 0,
    ("allcourt", "allcourt"): 0,
    ("baseliner", "counterpuncher"): 1,
    ("baseliner", "bigserver"): -1,
    ("baseliner", "baseliner"): 0,
    ("baseliner", "allcourt"): -1,
    ("bigserver", "counterpuncher"): 2,
    ("bigserver", "baseliner"): 1,
    ("bigserver", "bigserver"): 0,
    ("bigserver", "allcourt"): 0,
    ("counterpuncher", "bigserver"): -2,
    ("counterpuncher", "baseliner"): -1,
    ("counterpuncher", "allcourt"): -2,
    ("counterpuncher", "counterpuncher"): 0,
}

# Oppervlak voordeel per stijl
SURFACE_ADVANTAGE = {
    "Clay": {
        "allcourt": 1,
        "counterpuncher": 2,
        "baseliner": 1,
        "bigserver": -1,
    },
    "Grass": {
        "allcourt": 1,
        "bigserver": 2,
        "baseliner": 0,
        "counterpuncher": -1,
    },
    "Hard (outdoor)": {
        "allcourt": 1,
        "bigserver": 1,
        "baseliner": 1,
        "counterpuncher": 0,
    },
    "Hard (indoor)": {
        "allcourt": 0,
        "bigserver": 2,
        "baseliner": 1,
        "counterpuncher": -1,
    },
}
